### ISSUE TITLE
Deflection angle accuracy could be improved?

### ISSUE THREAD

**Issue by drphilmarshall** [wmorning/EvilLens#20]
I see tens of percent error in the central regions... Is this good enough, @yasharhezaveh? I'm guessing no, but I might be wrong. What's the acid test, @wmorning ?

**Comment by wmorning** [comment]
The accuracy of numerical integration WRT an analytic solution for an SIE has been improved (marginally), and the errors on the deflection angle are getting nearer to the milliarcsecond level (not there yet).  Still more to do here I think, but I thought I'd share the update.

**Comment by drphilmarshall** [comment]
Good work. This is the good fight.

**Comment by yasharhezaveh** [comment]
good progress Warren!
that sounds great.
The deflections that we'll be trying to model are of the order of a few
milli-arcsec (from substructure). So ideally we'll need the errors to be a
bit smaller.  Is this only a matter of increasing resolution? or are there
some systematics?

**Comment by wmorning** [comment]
Right now there are some systematics.  I think I might know why they exist though.

although I should probably talk to one of you to figure out if my solution is a good way to fix it, since it would change some aspects of the code significantly.

**Comment by yasharhezaveh** [comment]
if you're on campus tomorrow, we can meet and chat in the afternoon?
Y

**Comment by wmorning** [comment]
Sounds good.

**Comment by drphilmarshall** [comment]
Great! I just checked the "Deflection Angle Test" notebook, and it doesn't
show your results proving that the alphas are now computed with sufficient
accuracy - worth quickly updating this?

http://nbviewer.ipython.org/github/wmorning/EvilLens/blob/master/DeflectionTest.ipynb

**Comment by wmorning** [comment]
Good call.  New notebook is pushed to github.

**Comment by drphilmarshall** [comment]
Nice! I switched to RMS percentage accuracy as a metric for success, and
added a couple of notes. On to the next test! (#36 I guess)
