### ISSUE TITLE
Can we run EvilLens example from within casapy?

### ISSUE THREAD

**Issue by wmorning** [wmorning/EvilLens#34]

**Comment by wmorning** [comment]
casapy will let us run EvilLens examples provided it is able to import astropy.  It will be less easy to run casa in an ipynb notebook, although it doesn't say that it can't be done.

**Comment by wmorning** [comment]
Some progress on this front.  Using something called drivecasa (http://drive-casa.readthedocs.org/en/latest/index.html), I can now run CASA scripts from a python console.

**Comment by drphilmarshall** [comment]
Good! Looks like fairly simple code - you might need to (and be able to)
tweak it as you go, but I notice it comes with no license and hence is
copyright. Having said that, [Tim seems to be happy for developers to
modify the code.](
http://drive-casa.readthedocs.org/en/master/introduction.html#developer-setup)
I'll write him an issue saying hi, and that you are using his code and may
fork it in future, and what's his licence/citation policy.

**Comment by wmorning** [comment]
I think with the saboteur now being successfully able to write sabotaged data, we can close this!
