### ISSUE TITLE
(understand and) fix signal to noise in CASA

### ISSUE THREAD

**Issue by yasharhezaveh** [wmorning/EvilLens#38]
Yours sims were great. The signal to noise is way too off though.

in CASA's simobserve task there's a variable called "inbright"
the description says: "scale surface brightness of brightest pixel e.g. "1.2Jy/pixel"
So, for example, if our entire image is just zero, with only one non-zero pixel at its center, if we set inbright=0.1 Jy then the whole source will be assumed to have a flux of 0.1 Jy.

Now, if we had two non-zero pixels in the image, where one was half the intensity of the other, by setting inbright=0.1 Jy, we're assuming that the source has a total flux of 0.15 (0.1 for the brightest pixel + 0.05 from the second pixel at half intensity).

For out simulations, right now, we want our entire image to have a flux of, say 0.08 Jy. This is the typical *observed* flux of bright strong lenses in *continuum* (continuum = dust emission).

so you have to work out what value to give inbright so that your source has a flux of 0.08 Jy.

**Comment by wmorning** [comment]
does CASA automatically normalize your data such that the brightest pixel has a value of "1" ?

If so, that may mean that we should normalize the data ourselves before loading it into CASA.

Either way, my first guess would be to use inbright = (0.08Jy)/sum(lens.image)  except just using the number that is produced when doing that in an ipython notebook.

Is there a way to get CASA to tell you the total simulated flux?

**Comment by yasharhezaveh** [comment]
you're missing one thing in there,,,, (I think) this is what you need to do:

inbright = (0.08) * max(lens.image) / sum(lens.image)

if you want to see what the total flux of the simulated observation is,
you'll need to analyze that data (e.g., make a dirty/clean image etc).

**Comment by wmorning** [comment]
I think you're right.  That will give Flux=0.08, assuming that CASA sets the value of the maximum pixel to inbright and normalizes everything else accordingly, which is what its description suggests that it does.  

I'll re-run the simulation with this new inbright, and send you the data.
