### ISSUE TITLE
generate a new mock data

### ISSUE THREAD

**Issue by yasharhezaveh** [wmorning/EvilLens#39]
hey warren,
you're first mock data was great. a very good start.
now let's generate another mock, with an elliptical lens and some orientation angle.
(not to get a perfect einstein ring).
Also, did you figure out the scaling of the lens mass (are you giving  it in terms of sigma? like km/s?, if so, then it's fine, you should be using a sigma close t0 200 km/s).

Y

**Comment by wmorning** [comment]
I use sigma when constructing a lens (I used sigma is exactly 200 for the last one), but I can also get a mass from that.  For the next data, I'll know the mass before I send it.

And I'm just running the new image through CASA, so it'll be headed your way shortly.
