### ISSUE TITLE
decorrelation sim

### ISSUE THREAD

**Issue by yasharhezaveh** [wmorning/EvilLens#43]
make 2 simulations (including noise, and one or more subhalos). One with decorrelation, another without.
Run the subhalo finder on both and compare the delta_chi2 maps of subhalos.

**Comment by wmorning** [comment]
@yasharhezaveh , over what averaging time should we be looking to bin the visibilities?

Also, in these sims, should we be using an antenna configuration similar to the cycle 2 data, or closer to that from SDP 81 or cycle 3?

**Comment by yasharhezaveh** [comment]
let's stick to cycle 2 data for now.
max baseline of 1.5 km .
Each visibility is integrated for about 6 seconds. So I think it makes
sense to have visibilities that are ~0.2 seconds and average every 30 of
them together to get a 6 second visibility,
Dan, thoughts?

**Comment by dmarrone** [comment]
I think that we should make the visibility dataset relatively small, but cover an appropriately large baseline range. This could be done by very sparse time sampling (a short integration every several minutes or something). We're going to run a fit with and without the corruption, and we want to see how much the answers change, so we just have to be sure that we use the same data with the same random thermal noise added in both fits. 

As for the time averaging, it should probably be matched by a similar level of spatial averaging. If you have a phase screen moving at 12m/s and sample it 5x/sec, you're effectively putting 5 phase cells across the telescope aperture in one direction. Do you have 5 phase cells in the perpendicular direction, and are you averaging the phase across a circle of 12m diameter?

**Comment by wmorning** [comment]
As of right now, we're convolving the phase screen with a 12m diameter tophat kernel to mimic the ALMA antennas (using astropy.convolution).  As for the spatial averaging, I was planning on putting in phase cells that are 1-5m in size, this way we'll be sampling a different cell at each time step, although the neighboring cells within 6m in any direction will contribute to the phase.  I'm not sure if this answers your question about the cells in the perpendicular direction though (the size of phase cells in both directions are the same if that helps).
