### ISSUE TITLE
ideal antenna configuration

### ISSUE THREAD

**Issue by yasharhezaveh** [wmorning/EvilLens#46]
generate a few mock observations for identical lens/source/noise/etc with only different antenna configurations (i.e., uv coverage).  Calculate subhalo delta_chi2 maps for them. Which antenna configuration results in best subhalo constraints? (i.e., higher delta_chi2).  

Repeat this for a few different source structures. Presumably for sources with smaller clumps longer baselines should help.

**Comment by wmorning** [comment]
Results from this used in Cycle 4 ALMA proposal.  Accepted with grade A rating!
